config/routes.rb
Rails.application.routes.draw do
    root 'pages#main'
  
    get '/', to: 'pages#main'
    get '/about', to: 'pages#about'
    get '/help', to: 'pages#help'
    get '/signup', to: 'users#new'
    resources :users
    resources :userposts
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	before_save { email.downcase! }
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/models/userpost.rb
class Userpost < ApplicationRecord
	belongs_to :user
	validates :content, length: { maximum: 140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
  	render html: "Rghost is here, glory to holy regexp!"
  end

end

app/controllers/pages_controller.rb
include ApplicationHelper

class PagesController < ApplicationController
  def index
  end
  def main
  end

  def about
  end

  def help
  end
  
end

app/controllers/userposts_controller.rb
class UserpostsController < ApplicationController
  before_action :set_userpost, only: [:show, :edit, :update, :destroy]

  # GET /userposts
  # GET /userposts.json
  def index
    @userposts = Userpost.all
  end

  # GET /userposts/1
  # GET /userposts/1.json
  def show
  end

  # GET /userposts/new
  def new
    @userpost = Userpost.new
  end

  # GET /userposts/1/edit
  def edit
  end

  # POST /userposts
  # POST /userposts.json
  def create
    @userpost = Userpost.new(userpost_params)

    respond_to do |format|
      if @userpost.save
        format.html { redirect_to @userpost, notice: 'Userpost was successfully created.' }
        format.json { render :show, status: :created, location: @userpost }
      else
        format.html { render :new }
        format.json { render json: @userpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /userposts/1
  # PATCH/PUT /userposts/1.json
  def update
    respond_to do |format|
      if @userpost.update(userpost_params)
        format.html { redirect_to @userpost, notice: 'Userpost was successfully updated.' }
        format.json { render :show, status: :ok, location: @userpost }
      else
        format.html { render :edit }
        format.json { render json: @userpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /userposts/1
  # DELETE /userposts/1.json
  def destroy
    @userpost.destroy
    respond_to do |format|
      format.html { redirect_to userposts_url, notice: 'Userpost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_userpost
      @userpost = Userpost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def userpost_params
      params.require(:userpost).permit(:content, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	#Returns the full title 
	def full_title(page_title = '')
 base_title = "Static and Users"
 if page_title.empty?
 	base_title
 else
 	page_title + " | " + base_title
 end
end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/userposts_helper.rb
module UserpostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
   Its a <a href="https://en.wikipedia.org/wiki/British_Shorthair">British Shorthair</a>
  </small>
  <nav>
   <ul>
    <li><%= link_to "About", about_path %></li>
    </ul>
  </nav>
 </footer>

app/views/layouts/_header.html.erb
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
       <%= link_to "Static n Users", root_path , id: "logo" %>
        <nav>
         <ul class="nav navbar-nav navbar-right">
           <li><%= link_to "Main", root_path %></li>
           <li><%= link_to "Help", help_path %></li>
           <li><%= link_to "Log in", '#' %></li>
         </ul>
        </nav>
       </div>
      </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <%= render 'layouts/header' %>
      <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
      </div>
  </body>
</html>

app/views/pages/about.html.erb
<% provide(:title, "About") %>
<h1>Static and Users</h1>
<p>
This is about page for Static and Users App.  
Read about what you need to know about british shorthair
<a href=https://www.petful.com/cat-breeds/british-shorthair/>British Shorthair Cat</a>
</p>

app/views/pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Static and Users</h1>
<p>
This is help page for Static and Users App.
  Go get help there: 
<a href="https://www.apache.org">Apache!</a>
</p>

app/views/pages/main.html.erb
<div class="center jumbotron">
<h1>Static and Users</h1>

<h2>
 This is a home page for Static and Users App! <br/>
 Bad, bad cat!
</h2>

<%= link_to "Sign up now!", signup_path , class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("cat1.jpg", alt: "Cat"), 
            'https://cl.ly/182o1U2o2T0O' %>

<%= link_to image_tag("cat2.jpg", alt: "Cats") %>


            

app/views/userposts/_form.html.erb
<%= form_with(model: userpost, local: true) do |form| %>
  <% if userpost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(userpost.errors.count, "error") %> prohibited this userpost from being saved:</h2>

      <ul>
      <% userpost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :userpost_content %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :userpost_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/userposts/edit.html.erb
<h1>Editing Userpost</h1>

<%= render 'form', userpost: @userpost %>

<%= link_to 'Show', @userpost %> |
<%= link_to 'Back', userposts_path %>

app/views/userposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Userposts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @userposts.each do |userpost| %>
      <tr>
        <td><%= userpost.content %></td>
        <td><%= userpost.user_id %></td>
        <td><%= link_to 'Show', userpost %></td>
        <td><%= link_to 'Edit', edit_userpost_path(userpost) %></td>
        <td><%= link_to 'Destroy', userpost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Userpost', new_userpost_path %>

app/views/userposts/new.html.erb
<h1>New Userpost</h1>

<%= render 'form', userpost: @userpost %>

<%= link_to 'Back', userposts_path %>

app/views/userposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @userpost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @userpost.user_id %>
</p>

<%= link_to 'Edit', edit_userpost_path(@userpost) %> |
<%= link_to 'Back', userposts_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<h1>Sign Up</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>